workflows:
  react-native:
    name: reactnativeappsigning
    environment:
      groups:
        - carket
      vars:
        XCODE_WORKSPACE: 'Carket'
        XCODE_SCHEME: 'Carket'
      node: latest
    scripts:
      - npm install
      - echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - cd android
        ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/**/*.apk
